### PR TITLE
Azata Zippy Magic Feature, Transmutation Supremacy, and Bug Fixes

### LINKED ISSUE #18: Azata Zippy Magic Superpower with Buffs
### Spell Ability Description 

Wiki Link: [Azata Zippy Magic Superpower](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Zippy+Magic)

> Whenever the Azata casts a spell that targets individual creatures, not areas, the spell affects one additional creature within a 30 foot radius from the target. If the target is an enemy, the spell affects one additional enemy; **_if the target is an ally, the spell affects one additional ally._**

**Relevance**
When casting a single target buff from an Azata who has Zippy Magic, that buff will apply to a second ally.  For example, such an Azata casting Mage Armor on one ally will automatically cast Mage Armor on a second ally.  It is possible (but tedious) to control which ally receives the buff by moving all other allied characters outside a 30 ft radius.

**Desired Solution**
The ideal solution would allow the selection of a spell (targeting one character) cast from the main character (Azata with Zippy Magic) to apply to a second character.  

A solution should also account for the Azata being a brown fur arcanist, and take [Powerful Change](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Powerful+Change) and [Share Transmutation](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Share+Transmutation) into consideration.

### LINKED ISSUE #19: Remove fixed paths to D: in the csproj file
**Describe the bug**
There are fixed paths to D: in the csproj file.  This prevents building a cloned copy of the repository on a different computer.

**Expected behavior**
The paths should be relative paths using the environment variable WrathPathDebug

### LINKED ISSUE #20: Add missing \ for InputLegacyModule path in csproj file
**Describe the bug**
There is a missing \ in the path for the InputLegacyModule in the csproj file.  This prevents building this cloned repo on a separate computer.

**Expected behavior**
Include a \ so the path is correct.

### LINKED ISSUE #21: Missing assets in Assets\icons folder
**Describe the bug**
All .png files are missing from the Assets\icons folder.  This prevents building the project from a cloned copy of the repository.

**Expected behavior**
All assets should be included.

### LINKED ISSUE #22: Unnecessary WrathPath environment variable in csproj file
**Describe the bug**
The WrathPath environment variable in the csproj file points to the same location as the WrathPathDebug environment variable.  This makes it necessary to include two environment variables for building this project.

**Expected behavior**
Change WrathPath to WrathPathDebug so that only one environment variable is needed.

### LINKED ISSUE #23: Readme.md could provide information to help with building this repo
**Is your feature request related to a problem? Please describe.**
The Readme.md file provides little context to using this repository

**Describe the solution you'd like**
Include helpful information for this Pathfinder Mod

### LINKED ISSUE #25: Transmutation Supremacy Enhancements not Implemented for Powerful Change/Share Transmutation
**Describe the bug**
[Transmutation Supremacy](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Transmutation+Supremacy) is the Level 20 capstone ability for [Brown-Fur Transmuter](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Brown-fur+Transmuter).  It states:

> At 20th level, the brown-fur transmuter learns to fully master the power of transmutation. Whenever she casts a transmutation spell, it is treated as it were affected by the Extend Spell feat without altering the casting time or slot used. (She cannot then alter its duration again with the Extend Spell feat). **Whenever she uses her powerful change ability, the bonus increases by 4 instead of 2. Her share transmutation ability can now target a willing creature within 30 feet.**

Here are the bugs:
- For Powerful Change, the mod does not correctly apply the enhanced bonus.
- For Share Transmutation, the mod does not treat Share Mutation as ranged when using the animation casting (meaning the character will still run to target for touch casting).

**Expected behavior**
- For Powerful Change, the correct enhanced bonus should be applied.
- For Share Transmutation, the caster should treat the ability as ranged when using animation casting.

**Additional context**
I realized this was missing in the mod as I was working on #18.  As I have a brown-fur in my party, this is an ability I want to have available.

### LINKED ISSUE #26: Opposition school spells that use 2 spell slots not counted properly when selecting buff targets
**Describe the bug**
Consider these conditions:
- Caster is not spontaneous
- Caster has an opposition school (example: Divination)
- Caster slots a spell from the opposition school (example: True Seeing)

In this case, the spell requires two spell slots (per 1 cast).  

Then in the mod, select the spell (e.g. True Seeing) from the opposition school and select targets.  The mod will allow you to select 2 targets per the two spell slots consumed - this is incorrect.  

**Expected behavior**
The mod should only allow 1 target to be selected per 2 spell slots when using a spell from an opposition school.

### LINKED ISSUE #27: Arcane Reservoir point consumed when using Share Transmutation on self
**Is your feature request related to a problem? Please describe.**
The game allows a brown-fur transmuter to spend an arcane reservoir point on Share Transmutation and consume that point when casting on self.  The buff bot mimics this behavior.  However in the buff bot it's not possible to prevent casting the point on the caster if one desires to use for other allies too.

**Describe the solution you'd like**
Automatically do not spend an arcane reservoir point for Share Transmutation when casting on self.

Thanks @Cyrix for the suggestion

### PR DESCRIPTION
**Pull request by birick**
The primary purpose of this pull request is to add a new feature allowing control of secondary buffs when using the Azata Zippy Magic superpower.  It also adds features to account for Transmutation Supremacy enhancements to Powerful Change / Share Transmutation and prevent spending an arcane reservoir point when casting a spell with Share Transmutation on self.  Finally, it includes a number of bug fixes and other small changes.

Addresses and closes the following:
- (Primary Feature) Closes #18 
- (Feature) Closes #25 
- (Feature) Closes #27 
- (Bug Fix) Closes #26 
- (Bug Fix) Closes #19 
- (Bug Fix) Closes #20 
- (Bug Fix) Closes #21 
- (Bug Fix) Closes #22 
- (Quality of Life) Closes #23

This pull request includes updated information in the Changelog.md file, and increments the version to 5.1.0.

### CODE REVIEW

**Comment by birick** [comment]
I did my best to provide translations for all languages from Google translate.  If anyone can provide better translations, I'll incorporate in the request.

**Comment by birick** [comment]
I realized today that a significant feature for Brown-Fur Transmuters was missing in the mod.  The capstone ability for Level 20 Brown-Furs was never implemented, which means the mod will not apply enhanced versions of Powerful Change/Share Transmutation if the character has Transmutation Supremacy.

So, I've filed #25 and went ahead and implemented the enhanced versions of Powerful Change/Share Transmutation as appropriate.  In the process, I found the engine casting logic increasingly repetitive and difficult.  So I unified the engine casting logic to remove redundancy and make spell modifying as required by these abilities to be easier.

**Comment by birick** [comment]
Per advice, I've removed the BuffProvider from CastTask.  And the changelog has been updated with the new Transmutation Supremacy enhancements.

**Comment by birick** [comment]
Fixed a small issue between Azata Zippy Magic and the arcane reservoir if the reservoir is empty on a secondary cast.

**Comment by birick** [comment]
I found a bug I'm currently working on.  If casting the last secondary spell slot for a spell level with Zippy Magic, then the spell is canceled before the handler adjusts the spell cost.  Working on solution...

**Comment by birick** [comment]
I believe I've fixed the bug previously found.  Here's a more detailed explanation
- Caster is an Azata controlling secondary buffs
- Caster has expended all spell slots and is casting final secondary buff (which should be free)
- If using the animated engine, then the secondary buff was canceled because no spell slot was available.  The instant engine worked as expected.

The problem is that the commands the animated engine uses has no handler to adjust the spell slot cost before the slots are checked for being available.  So to fix, I changed the behavior to add a spell slot so that the secondary cast would have a slot to expend regardless of engine being used.

This fix turned out to be a little harder than expected, but I believe it is working correctly now.

**Comment by birick** [comment]
The IsAOE flag is not the same as IsMass.  Bug found and corrected with Frightful Aspect.

**Comment by birick** [comment]
Previously, I've mainly done testing with spontaneous casters.  I switched to testing non-spontaneous casters and fixed a small bug for Azata Zippy magic.  While at it, I corrected an existing bug related opposition school spells - see #26.

**Comment by birick** [comment]
Changelog updated with bug fix for opposition school spell bug

**Comment by birick** [comment]
Implement new feature to prevent spending an Arcane Reservoir point when using Share Transmutation on self.  This should resolve #27.

**Comment by birick** [comment]
Fixed a null exception bug for Light.  This occurs when a non-spontaneous spell is in a spontaneous caster book.  Example is Light.

**Comment by birick** [comment]
Code is starting to look pretty stable.  I've tested a large number of buffs in the game now, and they seem to be working as expected.  Here's a test with 250 buffs cast.

image

**Comment by birick** [comment]
It seems like OwlCat changed eventing in the 2.0.3i patch and casting stopped working as expected.  Updated event handling to work now with 2.0.3i (it should be backward compatible, but not tested).

**Comment by birick** [comment]
I have meticulously tested casting 300 spells at one time and keeping track of the results.  I see 2 bugs remaining.

First bug: When casting a spell with a retention (e.g. Powerful Change), it's possible the event bus will hold the retention across spells when using the Instant engine.  This has to do with how the Instant engine batches spells and casts them at the same time.  This bug is random in what the retention applies to and is difficult to reproduce.  It existed in the original algorithm, but no one noticed.

Second bug: When casting spells with material components (e.g. Legendary Proportions) while also using Azata Zippy Magic, the material components are spent twice (for each cast).  It should just spend the components once.

Will work on fixing these too.

**Comment by factubsio** [comment]
Do you want me to merge now or wait for material costs/instant bugs?
[19:53]bubbles: Can we fix the instant bug by limiting each caster to 1 per batch
[19:53]bubbles: I forget what delay there is currently 🤔
[19:54]bubbles: hmm 50ms
[19:55]bubbles: Ok we can at least disallow brownfur in same batch
[19:55]bubbles: so instead of statically batching each time we just try to fill the batch with stuff, applying some constraints
[19:55]bubbles: and try to do at least 1 brownfur (if available)

**Comment by birick** [comment]
I was thinking a similar solution - if the spell has a retention, then cast by itself, otherwise batch as usual

**Comment by birick** [comment]
I've fixed both issues.

**Instant Engine casting routine**

For the Instant Engine casting routine, I first grabbed the LINQ batching extension used in dotnet (yea... .NET Framework is old!!!) and integrated to the project.  The Microsoft source code is at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Chunk.cs.

I then change up the retention checks a bit so that the engine was aware of what retentions are necessary.  Batching is then split into two parts.  The first part creates batches of 8 spells (as before), but only includes spells that don't require a retention.  After those batches are cast, the tasks that do require a retention are cast one at a time.  This allows for the retention to be set and then released before another spell is cast, preventing retention conflicts.

This could be made a little more fancy by grouping casters, but it's unlikely a team will have multiple bfts to which this would apply, so keeping the code simple for maintainability.

I have tested several times now, and the random retention bugs I was seeing are gone.

**Azata Zippy Magic Secondary Buff Material Cost**

This wasn't too difficult.  Just by inspecting the code, it was easy enough to see how to check for spell material costs.  Examining the source code used in the toybox (e.g. https://github.com/cabarius/ToyBox/blob/2eb743df1548be2e77f63cfaef40b4b5ffa6c0d1/ToyBox/classes/MainUI/Browser/BlueprintAction.cs) it was easy enough to see how to add materials back to the player's inventory.  So just like with the spell slot solution, the material components are added to the inventory so that they can be spent with no net materials spent.  This will show in the log as components being added and then spent.

image

I've tested with Legendary Proportions, Protection from Spells, True Seeing, and Stoneskin

**Comment by factubsio** [comment]
Do we need to do something for patch or still good to go?

**Comment by birick** [comment]
Good to go

**Pull request merged**
