### PR TITLE
Fix incorrectly applied buffs when out of Arcanist points

### PR DESCRIPTION
**Pull request by Bobster1246**
One issue with the BubbleBuffs mods is that it doesn't handle Arcanist points well when using a Brownfur Transmuter.

If you run out of points, Bubble will incorrectly apply the buffs without the special Brownfur options.

This is generally not what you want to do. You are using a Brownfur Transmuter for a reason!

This patch fixes the issue by stopping buff application when you run out of arcanist points.

### CODE REVIEW

**Comment by factubsio** [comment]
I've not forgotten about this, I think I broke the merge with the fixes for 1.4 do you want me to fix up the pr or will you?

**Comment by Bobster1246** [comment]
Can you fix the PR and test it? I don't have the 1.4 beta installed yet so I can't test it properly.

**Comment by factubsio** [comment]
> Can you fix the PR and test it? I don't have the 1.4 beta installed yet so I can't test it properly.

Yeah will do when I get some time. 👍

**Comment by Bobster1246** [comment]
@factubsio I rebased my patches to the latest master branch and tested them with 1.4!

This should be good to merge now

**Comment by factubsio** [comment]
I merged this manually :-(

**Pull request closed without merging**
